version: '3'

services:
  codesys:
    image: docker.io/joyja/codesys-control:version-4.8.0
    ports:
      - 4840:4840
      - 11740:11740
    volumes:
      - codesys-data:/data
      - ./CODESYSControl_User.cfg:/etc/CODESYSControl_User.cfg:ro
      - codesys-pvc:/var/opt/codesys

volumes:
  codesys-data:
  codesys-pvc:
